# Generated by Django 4.2.3 on 2023-08-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('chatContent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.task')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
